### ISSUE TITLE
DreamSpace no collission, falling through the floor.

### ISSUE THREAD

**Issue by h3ll0-w00rld** [Divine-Star-Software/DivineVoxelEngine#10]
When running DreamSpace, i fall through the floor, but can elevate myself (somewhat) to the top by holding space.
And this shows up in terminal when I open DreamSpace, LitFluidTest and NoiseWorld.
[15419:0706/154039.715956:ERROR:shared_image_manager.cc(228)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.

This might be my side problem, not 100% sure.
OS: Linux (arch)

**Comment by lucasdamianjohnson** [comment]
Hello, 
So, I just fixed that issue with falling through the floor. I was doing some testing on releasing the cached geometry data. And some examples actually use Babylon's built-in collision system instead of the AABB collision system I am working on.
I will be adding engine settings in the future to auto-clear the mesh data. 
But yes sorry about that. If you run on a pull on the repo now should fix the issue. 

As for the other error is this in the Dev Tools console or the actual console when you run Electron? 
Does it affect the examples or does it just show the error? 

I get this message when I run it on Windows:
```console
[3556:0706/100013.843:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
```

But it has never affected anything. I think it may just be an issue with Electron.

**Comment by lucasdamianjohnson** [comment]
@h3ll0-w00rld Yes for the noise world it can take like 30+ seconds for it to fully build. 
It generates the whole world then does all the sunlight updates then builds itself. 
On my machine, it can do it in like 30 seconds but my machine has 6 cores and it makes use of all of them.

**Comment by h3ll0-w00rld** [comment]
I have a potato from 2012 CPU, and RX 460, I'd imagine it will take a few solid minutes. As of now, I'm intrigued by this. If this is a 1 person/small team project, mad respect for how good it is.

**Comment by lucasdamianjohnson** [comment]
@h3ll0-w00rld  
Umm yeah, this engine is not exactly designed to run on a potato lol. 
But I appreciate the attempt. 
I built this on a 6 core. 16 GB Ram, with an RTX 2060. So, not like the highest-end machine but far from a potato. 

And yes this was all built by me. Expect of course Babylon.Js which is the render/game engine I am using.

**Comment by h3ll0-w00rld** [comment]
Yeah this runs (mostly) smooth on lower end A8-5600k 3.6 Quad core + RX 460 2GB and 16GB of RAM. Does take a while (cuz i am loading this from HDD not my main SSD). It's pretty cool how one man can make smthng this cool. Keep it up, I'll do some other testing in free time.

**Comment by lucasdamianjohnson** [comment]
Well, I guess that is good to hear. 
But thank you!
I am here to answer any questions about it if need be. 
May start a discord server someday so people can get direct help from me but idk.

**Comment by lucasdamianjohnson** [comment]
I am gonna close this issue out since it has been fixed.
